# Generated by Django 5.1.7 on 2025-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='certification_images/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('credentials_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
