# Generated by Django 5.1.7 on 2025-09-13 21:14

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_name_project_picture_project_slug_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=taggit.managers.TaggableManager(help_text='Technologies used (e.g. python, django, tailwind)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
