# Generated by Django 5.1.7 on 2025-09-21 22:27

import apps.projects.models
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_picture_remove_project_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(validators=[apps.projects.models.validate_max_430]),
        ),
    ]
