# Generated by Django 5.1.7 on 2025-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(default='Me', max_length=255)),
            ],
        ),
    ]
