# Generated by Django 5.1.7 on 2025-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='N/A', max_length=100, unique=True),
        ),
    ]
