# Generated by Django 5.1.7 on 2025-03-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
