# Generated by Django 5.1.7 on 2025-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_by',
            field=models.CharField(default='S. Dinev', max_length=255),
        ),
    ]
