import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes"; 

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`flex flex-col min-h-screen ${figtree.variable} antialiased`} >
        <ThemeProvider
          attribute="class"      // uses Tailwind dark mode classes
          defaultTheme="dark"    // default to dark
          enableSystem={false}   // ignore system theme
        ></ThemeProvider>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
